### PR TITLE
Feature/travis test

### PR DESCRIPTION
**Pull request by venabled**
Added some travis.ci testing, including some fixes to get the tests to pass on python34. Also did *some* PEP8 cleanup.

### CODE REVIEW

**Comment by venabled** [comment]
Was doing this to hopefully get the build ready to release onto PyPi.

**Comment by hamid-m** [comment]
Venabled, thanks for the changes.  Three things I wanted to ask: 

1. Can you say more about the travicCI yaml?  It's new to me and I understood it as a way to check the build.  Is that what others use to embed "build status" symbols in their `README.md`?  

2. Is that required or related to getting onto PyPi?  Or was that just the PEP8 fixes? 

3. Does the module work on Python 3.x?  I've never tested such but think it should be cross compatible.

**Comment by venabled** [comment]
Hamid, I'm pretty new to python packaging as well so I'm kind of learning as I go, but let me try to answer: 

>Can you say more about the travicCI yaml? It's new to me and I understood it as a way to check the build. Is that what others use to embed "build status" symbols in their README.md?

[travis-ci](http://docs.travis-ci.com/user/getting-started/) is a hosted continuous integration system thats super integrated with GitHub. Basically its just a really easy way to build the code and run test suites in different environments. I think most projects that you see with a build status are using travis. 

The YAML file just tells travis how to set up different build environments and which test suites / coverage checks to run. I stole one from [another project](https://github.com/shrimped/dzmq). This one uses [miniconda](http://conda.pydata.org/miniconda.html) instead of pip/virtualenv to do package management (just out of habit, but conda is nice if you have some complicated dependencies). This one sets up both a python2.7 and a python3.4 environment and then runs the nosetest suite.

> Is that required or related to getting onto PyPi? Or was that just the PEP8 fixes?

I don't think either are really required. PEP8 I was just doing because the linter in Sublime's Anaconda was lighting up the code so I figured that while I was in there might as well do some work :) I figured just adding in CI support and python3 support will end up with less issues in the long run and let us put up the build badges. [Here's the docs](https://python-packaging-user-guide.readthedocs.org/en/latest/distributing.html). Some packages have release guidelines we could borrow from, e.g. [bokeh](https://github.com/bokeh/bokeh/wiki/BEP-2:-Release-Management)

> Does the module work on Python 3.x? I've never tested such but think it should be cross compatible.

It worked with the exception of some of the python2 styled print statements in utils.py, and some of the relative import stuff you can see in the commits. As of now it's [building fine](https://travis-ci.org/venabled/NavPy) on python 2.7 and 3.4.

**Comment by hamid-m** [comment]
That helps and looks like a step in the right direction.  Seems like many major projects are using it to keep tracking of building fine ([scipy](https://travis-ci.org/scipy/scipy) and [ipython](https://travis-ci.org/ipython/ipython))
I'll create an issue to resolve the minor Python 3.x compatibility corrections we need.

**Pull request merged**
